myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'
urlpatterns = [
    path('',views.index),
    path('products/',views.products,name="products"),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('products/add/',views.add_product,name='add_product'),
    path('products/update/<int:id>/',views.update_product,name='update_product'),
    path('products/delete/<int:id>/',views.delete_product,name='delete_product'),
    path('products/mylistings',views.my_listings,name="mylistings"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='users'
urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/login.html'),name='logout'),
    path('profile',views.profile,name='profile'),
    path('createprofile/',views.create_profile,name='create_profile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='seller_profile'),
]

myapp/models.py
from email.mime import image
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
    seller_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    name=models.CharField(max_length=70)
    price=models.IntegerField()
    desc=models.CharField(max_length=200)
    image=models.ImageField(blank=True)

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    contact_num=models.CharField(max_length=100,default="99999")

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True,widget = forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'urmailid@gmail.com'}))
    username=forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'user123'}))
    password1=forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2=forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model=User
        fields=("email","username","password1","password2")
    def save(self,commit=True):
        user=super(NewUserForm,self).save(commit=False)
        user.email=self.cleaned_data['email']
        if(commit):
            user.save()
        return user

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Product
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    return HttpResponse("hello There")

def products(request):
    page_obj = listOfProducts=Product.objects.all()
    product_name=request.GET.get('product_name')
    if(product_name!='' and product_name is not None):
        page_obj=listOfProducts.filter(name__icontains=product_name)
    paginator=Paginator(page_obj,3)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    context={
        'page_obj' : page_obj
    }
    return render(request,'myapp/index.html',context)

class ProductListView(ListView):
    model=Product
    template_name='myapp/index.html'
    context_object_name='products'

def product_detail(request,id):
    detailedProduct=Product.objects.get(id=id)
    context={
        'product' : detailedProduct
    }
    return render(request,'myapp/detail.html',context)

class ProductDetailView(DetailView):
    model=Product 
    template_name='myapp/detail.html'
    context='product'

@login_required
def add_product(request):
    if(request.method=='POST'):
        name=request.POST.get('name')
        price=request.POST.get('price')
        desc=request.POST.get('desc')
        image=request.FILES['upload']
        seller_name=request.user
        product = Product(name=name,price=price,desc=desc,image=image,seller_name=seller_name)
        product.save()
    return render(request,'myapp/addproduct.html')

def update_product(request,id):
    product=Product.objects.get(id=id)
    if(request.method=='POST'):
        product.name  =  request.POST.get('name')
        product.price =  request.POST.get('price')
        product.desc  =  request.POST.get('desc')
        if(request.FILES.get('upload')):
            product.image =  request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    context={
        'product': product
    }
    return render(request,'myapp/updateproduct.html',context)

def delete_product(request,id):
    product=Product.objects.get(id=id)
    context={
        'product':product 
    } 
    if(request.method=='POST'):
        product.delete()
        return redirect('/myapp/products')
    return render(request,'myapp/deleteproduct.html',context)

def my_listings(request):
    product = Product.objects.filter(seller_name=request.user)
    context = {'products': product}
    return render(request, 'myapp/mylistings.html', context)

users/views.py
from django.shortcuts import render
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.
def register(request):
    if(request.method=='POST'):
        form=NewUserForm(request.POST)
        if(form.is_valid()):
            user=form.save()

    form = NewUserForm()
    context={
        'form':form,
    }
    return render(request,'users/register.html',context)

@login_required
def profile(request):
    return render(request,'users/profile.html')

def create_profile(request):
    if(request.method=='POST'):
        contact_num=request.POST.get('contact_number')
        if(request.FILES['upload']):
            image=request.FILES['upload']
        user=request.user
        profile=Profile(user=user,image=image,contact_num=contact_num)
        profile.save()
    return render(request,'users/createprofile.html')

def seller_profile(request,id):
    seller=User.objects.get(id=id)
    context={
        'seller':seller
    }
    return render(request,'users/seller_profile.html',context)

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">Add Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 mx-auto px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Name" type="text" name="name" id="name">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Price" type="text" name="price" id="price">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Description" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image</label>
        <input type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <input class="bg-green-500 text-white px-5 py-2 rounded" type="submit" name="Add Product" value="Add Product">
    </div>
</form>

{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class="dark:bg-gray-500">
    <nav class="bg-gray-200 shadow-lg sticky top-0">
        <div class="mx-auto px-4 max-w-6xl">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div>
                        <a href="" class="flex items-center py-4 px-2">
                            <img class="h-8 w-8" src="{% static 'images/shopping.png' %}" alt="">
                            <span class="text-gray-700 text-lg font-semibold">Sell & Buy</span>
                        </a>
                    </div>
                    <div class="flex items-center space-x-1">
                        <a href="{% url 'myapp:products' %}" class="py-4 px-2 text-gray-700 font-semibold">Home</a>
                        <a href="{% url 'myapp:add_product' %}" class="py-4 px-2 text-gray-700 font-semibold">Post Ad</a>
                        <a href="{% url 'myapp:products' %}" class="py-4 px-2 text-gray-700 font-semibold">View Products</a>
                        {% if user.is_authenticated %}
                        <a class="py-4 px-2 text-gray-700 font-semibold" href="{% url 'myapp:mylistings' %}">MyListings</a>
                            <a class="py-4 px-2 text-gray-700 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                            <a class="py-4 px-2 text-gray-700 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                        {% else %}
                            <a class="py-4 px-2 text-gray-700 font-semibold" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

myapp/templates/myapp/deleteproduct.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">Delete Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 mx-auto rounded px-8 pt-6 pb-8 mb-4" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Are you sure you want to delete this product?</label>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">
            {{product.name}}
        </label>
    </div>
    <div class="mb-4">
        <img class="h-20 w-20" src="{{product.image.url}}" alt="">
    </div>
    <input  class="bg-red-500 text-white px-5 py-2"  type="submit" name="Confirm">

    <a class="button bg-green-500 px-5 py-3 text-white" href="{% url 'myapp:products' %}">Cancel</a>
</form>

{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10">
        <div class="mt-5 ">{{ product.name }}</div>
        <div class="mt-5 text-green-500">$ {{ product.price }}</div>
        <div class="mt-5 text-gray-700">{{ product.desc }}</div>
        <div class="mt-5">
            <a href="{% url 'users:seller_profile' product.seller_name.id %}">
                {{ product.seller_name }}
            </a>
        </div>
        <div class="mt-5 text-gray-700">Contact num :{{product.seller_name.profile.contact_num }}</div>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}



{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 lg:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="xl:inline">
                Premium Products
            </span>
            <span class="block text-green-600 xl:inline">
                Non Premium Prices
            </span>
        </h1>
        <p class="mt-3 text-base text-gray-900 sm:mt-15 sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl">
            Get the best quality used products across the globe.Free shipping
        </p>
    </div>

</main>
<div class="flex mt-5 p-10 justify-around">
    <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-900">
        Recent Products
    </h2>
    <div>
        <form method="GET">
            <input type="text" placeholder="Search Products"
                class="appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500"
                name="product_name" id="product_name">
        </form>
    </div>
</div>

<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 space-x-2 space-y-2">
    {% for product in page_obj %}
    <a href="{% url 'myapp:product_detail' product.id %}">
        <div class="rounded overflow-hidden shadow-lg">
            <img class="w-full" src="{{product.image.url}}" alt="">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{product.name}}</div>
                <div class="font-bold text-xl mb-2 ">Posted By : <span
                        class="text-indigo-400">{{product.seller_name}}</span></div>
                <div class="font-bold text-xl mb-2 text-green-600">$ {{product.price}}</div>
                <p class="text-gray-700 text-base">{{product.desc}}</p>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
<div class="flex justify-center items-center mb-20">
    <span>
        {% if page_obj.has_previous %}
        <a class="text-sm font-medium py-2 px-4 items-center inline-flex relative text-green-500 border border-green-600 z-10" href="?page=1">
            First
        </a>
        <a class="text-sm font-medium py-2 px-4 items-center inline-flex relative text-green-500 border border-green-600 z-10" href="?page={{page.obj_previous_page_number}}">
            Previous
        </a>
        {% endif %}
    </span>
    <span class="text-sm font-medium py-2 px-4 items-center inline-flex relative text-green-500 z-10 mx-2">
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>
    <span>
        {% if page_obj.has_next %}
        <a class="text-sm font-medium py-2 px-4 items-center inline-flex relative text-green-500 border border-green-600 z-10" href="?page={{page_obj.next_page_number}}">
            Next
        </a>
        <a class="text-sm font-medium py-2 px-4 items-center inline-flex relative text-green-500 border border-green-600 z-10" href="?page={{page_obj.paginator.num_pages}}">
            Last
        </a>
        {% endif %}
    </span>
</div>
{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="text-2xl m-10 p-10 font-bold">
    My Listings
</div>
{% for product in products %}

<div class="flex shadow-lg m-10 p-10 w-1/2 mx-auto">
    <span class="w-1/5">
        <img src="{{product.image.url}}" alt="" class="w-40 h-40">
    </span>
    <span class="w-2/5">
        <div class="font-bold text-gray-700">{{product.name}}</div>
        <div class="text-green-500">$ {{product.price}}</div>
        <div>{{product.desc}}</div>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-green-500 text-white font-bold px-5 py-2" href="{% url 'myapp:update_product' product.id %}">Edit</a>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-red-500 text-white font-bold px-5 py-2" href="">Delete</a>
    </span>
</div>

{% endfor %}

{% endblock %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">Update Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 mx-auto px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.name}}" type="text" name="name" id="name">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.price}}" type="text" name="price" id="price">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image</label>
        <input type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4 w-1/2 mx-auto">
        <input class="bg-green-500 text-white px-5 py-2 rounded" type="submit" name="Update Product" value="Update Product" id="">
    </div>
</form>

{% endblock %}

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Your Profile</h1>
<div class="container py-5">
    <form class="w-1/3 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Upload Profile Image</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                <input type="file" accept="image/*" name="upload" id="upload">
            </div>
        </div>
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Contact Number</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                <input type="text" name="contact_number" id="contact_number">
            </div>
        </div>
        <button type="submit" class="bg-green-500 text-white px-5 py-2">Register</button>
    </form>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Login User</h1>
<div class="container py-5">
    <form class="w-1/3 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST" action="">
        {% csrf_token %}
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight focus:outline-none">
                {{form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password}}
            </div>
        </div>
        <button type="submit" class="bg-green-500 text-white px-5 py-2">Login</button>
    </form>
    <div class="m-10">
        Don't have an account? <a class="text-indigo-500" href="{% url 'users:register' %}">Register</a>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="">
            <img class="w-36 h-36 rounded-full" src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            <p>{{user.username}}</p>
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            <p>{{user.profile.contact_num}}</p>
        </div>
    </div>
    <div>
        <a class="bg-green-500 text-white font-semibold px-3 py-2 border border-green-700 m-10" href="{% url 'users:create_profile' %}">Update Profile</a>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}

<h1 class="text-2xl m-10 font-bold">Register User</h1>
<div class="container py-5">
    <form class="w-1/3 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST" action="">
        {% csrf_token %}
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight ">
                {{form.username}}
            </div>
        </div>
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.email}}
            </div>
        </div>
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password1}}
            </div>
        </div>
        <div class="mb-2">
            <label for="" class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password2}}
            </div>
        </div>
        <button type="submit" class="bg-green-500 text-white px-5 py-2">Register</button>
    </form>
    <div class="m-10">
        Already have an account? <a class="text-indigo-500" href="{% url 'users:login' %}">Login</a>
    </div>
</div>

{% endblock %}

users/templates/users/seller_profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img class="w-36 h-36" src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            <p>{{seller.username}}</p>
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">
            <p>{{seller.profile.contact_num}}</p>
        </div>
    </div>
</div>

{% endblock %}